### ISSUE TITLE
WhatsApp Group

### ISSUE THREAD

**Issue by ctomasgm** [hectoraguirre18/aulas-dark#1]
Greetings Mr. PatitoGordito,

I can't see where´s the WhatsApp group to add a new issue.
I wish you can fix this as soon as possible.

Penguin out.

**Comment by ctomasgm** [comment]
5 minutes and no answers yet. What a bad service.

**Comment by hectoraguirre18** [comment]
Hello Mr. Lelouch, I'll take care of this, don't worry. I'm closing this issue now.
